### ISSUE TITLE
Foliendesign anpassen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/wba1-2015#1]
Da sollte bitte eine Anpassung an die neuen FH Farben und so rein.

**Comment by Plsr** [comment]
Design ist gepushed, hier gibts eine Testpräsentation: http://th-koeln.github.io/wba1-2015/2015-25-09-style-development/index.html#/

Die alten Folien sind davon noch nicht betroffen, wenn das so approved ist würde ich die source files entsprechend anpassen.

**Comment by cnoss** [comment]
Aus meiner Sicht erst mal ok. Können wir demnächst vielleicht mal eine weiter Iteration machen.
