### ISSUE TITLE
Prüfen ob Git-Client auf iMacs installiert ist.

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2015#11]

**Comment by jhfpereira** [comment]
Welche iMacs sind damit genau gemeint?
Wenn das das noch niemandem zugewiesen wurde, könnte ich das morgen (Mi, 07.Okt) direkt übernehmen oder zumindest dabei helfen.
Würde dann auch direkt schauen, ob sich für die Zwischenlagerung der Repos, evtl. auch die ADV-Cloud (per WebDAV) eignet, da jeder Student der eine GMID besitzt, scheinbar auch 1GB in der ADV-Cloud erhält.
