### ISSUE TITLE
Fälle vorbereiten

### ISSUE THREAD

**Issue by cnoss** [th-koeln/wba1-2015#12]

**Comment by koos** [comment]
soll ich auch einen fall dazusteuern?

—
Jan Kus 
Founder & CEO

Railslove GmbH 
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9 
Twitter @koos 
Skype jbvkoos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider 

* We're hackers&thinkers: http://hackersandthinkers.biz 
* this email brought to you by ✓ http://instantcheckmark.com ✓ *

**Comment by cnoss** [comment]
Wäre nicht schlecht. Muss aber nicht.

**Comment by koos** [comment]
@cnoss  fehlen dir konkrete Sachen in den Fällen?
