### ISSUE TITLE
Teilnehmer als Kolaboratoren hinzufügen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/wba1-2015#23]

**Comment by Plsr** [comment]
Kann ich leider momentan nicht machen, habe scheinbar keine Berechtigung für die Settings.

![screen shot 2015-10-19 at 16 18 59](https://cloud.githubusercontent.com/assets/3950661/10580299/251fde7a-767d-11e5-9455-2b0aa2b80d8e.png)

**Comment by jhfpereira** [comment]
Wenn wir schon dabei sind ... bin scheinbar auch nur ein Collaborator :)
