### ISSUE TITLE
Themen in Wiki eintragen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/wba1-2015#24]

**Comment by Plsr** [comment]
Kann da momentan nur mit den [Fotos](https://github.com/th-koeln/wba1-2015/wiki/03-Themen-der-Grupen) arbeiten, die ich gemacht habe. @vschaefer du hast die Zettel, oder?

**Comment by vschaefer** [comment]
Ja die habe ich. Ich versuche die Teams und Projekte heute Abend ins Wiki einzutragen.

**Comment by Plsr** [comment]
Kann dir das auch abnehmen wenn du mir die Zettel irgendwie zukommen lassen kannst oder schonmal auf Basis der Fotos anfangen wenn dir das hilft?

**Comment by vschaefer** [comment]
Wenn du Luft hast gerne :)

**Comment by vschaefer** [comment]
Wenn du Luft hast, gerne :)
Ich würde vier Spalten vorschlagen: laufende Nummer, Thema, Projektart und Teammitglieder.
Vielleicht kann man dem Wiki irgendwie beibringen, dass die Tabelle sortiertbar ist.

**Comment by Plsr** [comment]
Die meisten Themen sind eingetragen.

Einige Namen standen auf der Rückseite der Karte, einige konnte ich auf den Bildern nicht erkennen. Habe ich entsprechend gekennzeichnet.
