### ISSUE TITLE
Git push master origin (Wiki geht nicht)

### ISSUE THREAD

**Issue by TheChrissi1** [th-koeln/wba1-2015#32]
Hallo zusammen,

habe da ein Problem.
Wenn ich die Markdowndatei (für die Ausarbeitung) bei mir auf dem Rechner bearbeite, adde und commit, dann kann ich die Datei danach nicht in den master branch pushen. Da im Wiki ja nur der Master Branch angezeigt wird muss ich das ganze doch da rein pushen oder?

Bekomme da immer folgende Fehlermeldung:
"$ git push origin master
To https://github.com/th-koeln/wba1-2015.wiki.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/th-koeln/wba1-2015.wiki.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."

Habe auch vorher schon ein git pull origin master gemacht. Trozdem selbe Fehlermeldung.

Hat hier einer eine Lösung für mich?

Danke schon mal im Vorraus!

Schönen Abend noch.

Mit freundlichen Grüßen,
Christian Wolf

**Comment by vschaefer** [comment]
Hello,

ich könnte mir das so spontan nur so erklären, dass jemand noch mal in dem Moment etwas in den Master-Branch gepushed hat nachdem du gepullt hast.

Was für eine Meldung kommt denn wenn du `git status` in die Konsole eingibst?

**Comment by TheChrissi1** [comment]
Hallo,

habe es jetzt gerade wieder ausprobiert, funktioniert immer noch nicht (denke nicht das gerade wieder ein anderer was pushed.

Wenn ich git status mache kommt: 

"On branch HTTPWolf
nothing to commit, working directory clean"

Wüsste also echt nicht wo der Fehler liegt.

Grüße
Christian Wolf

**Comment by jhfpereira** [comment]
Hi,
versuch mal folgendes:

`git pull`
`git push`

Ich vermute, dass in der Zwischenzeit bereits weitere Änderungen von anderen Studenten "hochgepusht" wurden und dies zu deinem Problem führt.

Am besten du ziehst dir zuerst die Änderungen von origin (die Änderungen in dem auf GitHub liegenden Wiki-Repo), bevor du deine wieder auf origin "pusht".

Habe die Remotepoint- und Branch-Parameter weggelassen.
Kannst aber auch gerne versuchen, sie anzugeben.
Also:

`git pull origin master`
`git push origin master`


Meine Vermutung ist, dass du lokal liegende Änderungen in Form von Commits nicht pushen kannst, weil es ein Sicherheitsmechanismus von git ist.
Angenommen jemand hat Änderungen "hochgepusht" und man hat lokal an den selben Dateien Änderungen vorgenommen und versucht diese (nach einem add u. commit) auf origin zu pushen, besteht die Gefahr, dass es knallen könnte -> **Merge-Conflict**.
Deshalb wird von einem verlangt, dass man die in der Zwischenzeit von anderen gepushten Änderungen erst zieht (pull) um zu schauen, ob es zu Konfikten kommt, um dann in der Lage zu sein, diese beheben zu können. Nachdem man den Konflikt gelöst hat, kann man versuchen das Ganze wieder zu pushen.

Ich hoffe das löst dein Problem :)

**Comment by jhfpereira** [comment]
Sollte es immer noch nicht klappen, würde ich es mir gerne am Donnertag ansehen.

**Comment by TheChrissi1** [comment]
Hallo,

habe alles nochmal ausprobiert allerdings bekomme ich immer noch die selbe Fehlermeldung.
Auch wenn ich in den master-Branch wechesle das ganze pulle und wieder versuche aus meinem Branch in den master-Branch zu push.

Soweit ich mich erinnern kann habe ich meinen Branch nicht wieder in den master-Branch zurückgeführt.

Kannst du dir gerne morgen mal anschauen, ich übersehe da bestimmt irgendwas.

Schönen Abend noch.

Grüße
Christian Wolf

**Comment by jhfpereira** [comment]
Hi,
das ist sehr merkwürdig.
Glaube aber, dass wir das Problem schon gelöst kriegen.

Sprich mich morgen einfach darauf an :)

Dir ebenfalls einen schönen Abend und bis morgen.
